% AUTO-GENERATED FROM app.mlapp BY export_app_source.m.
% DO NOT EDIT THIS FILE DIRECTLY.
% Regenerate with: matlab -batch "export_app_source"

classdef app_exported < matlab.apps.AppBase

    % Properties that correspond to app components
    properties (Access = public)
        UIFigure                       matlab.ui.Figure
        HomePanel                      matlab.ui.container.Panel
        HomePanel_ContinueButton       matlab.ui.control.Button
        SelectDirectoryButton          matlab.ui.control.Button
        SelectDirectoryTextArea        matlab.ui.control.TextArea
        HomePanel_Label1               matlab.ui.control.Label
        LIFSeriesPanel                 matlab.ui.container.Panel
        LIFSeriesPanel_UmPerPixEditField  matlab.ui.control.NumericEditField
        EnterumperpixelEditFieldLabel  matlab.ui.control.Label
        LIFSeriesPanel_TextArea        matlab.ui.control.TextArea
        LIFSeriesTextAreaLabel         matlab.ui.control.Label
        LIFSeriesPanel_NextButton      matlab.ui.control.Button
        LIFSeriesPanel_LIFSeriesNumberEditField  matlab.ui.control.NumericEditField
        ChooseseriesinLIFLabel         matlab.ui.control.Label
        TIFFrequencyPanel              matlab.ui.container.Panel
        TIFFrequencyPanel_NextButton   matlab.ui.control.Button
        TIFFrequencyPanel_UmPerPixEditField  matlab.ui.control.NumericEditField
        EntermicronsperpixelLabel      matlab.ui.control.Label
        TIFFrequencyPanel_FrequencyEditField  matlab.ui.control.NumericEditField
        EnterthefrequencyofrecordingEditFieldLabel  matlab.ui.control.Label
        CroppingPanel                  matlab.ui.container.Panel
        CroppingPanel_Label            matlab.ui.control.Label
        ThresholdPanel                 matlab.ui.container.Panel
        ThresholdPanelLabel_3          matlab.ui.control.Label
        ThresholdPanelContinueButton   matlab.ui.control.Button
        ThresholdPanelBackButton       matlab.ui.control.Button
        ThresholdPanelLabel_2          matlab.ui.control.Label
        ThresholdPanelValueEditField   matlab.ui.control.NumericEditField
        ThresholdValueEditFieldLabel   matlab.ui.control.Label
        MaskingPanel                   matlab.ui.container.Panel
        Label_2                        matlab.ui.control.Label
        Label                          matlab.ui.control.Label
        DilationPanel                  matlab.ui.container.Panel
        DilationPanel_ContinueButton   matlab.ui.control.Button
        DilationPanel_SizeEditField    matlab.ui.control.NumericEditField
        WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel  matlab.ui.control.Label
        DilationPanel_Label2           matlab.ui.control.Label
        DilationPanel_Label1           matlab.ui.control.Label
        CappingPanel                   matlab.ui.container.Panel
        Label_3                        matlab.ui.control.Label
        CappingPanel_Label1            matlab.ui.control.Label
        SliceProgressPanel             matlab.ui.container.Panel
        SliceProgressPanel_Label       matlab.ui.control.Label
        RedoMaskButton                 matlab.ui.control.Button
        RunButton                      matlab.ui.control.Button
        SliceProgressPanel_TextArea    matlab.ui.control.TextArea
        ProgressTextAreaLabel          matlab.ui.control.Label
        RunComputationPanel            matlab.ui.container.Panel
        RunComputationPanel_TextArea   matlab.ui.control.TextArea
        ProgressTextAreaLabel_2        matlab.ui.control.Label
        SaveResultsButton              matlab.ui.control.Button
    end


    properties (Access = private)
        currentDir = fileparts(mfilename('fullpath'));
        defaultUigetdir
        filePath
    end

    properties (Access = public)
        waitingForInput = false;
        seriesCount = 1;
        maxPreviewFrames = 200;
        dsFactor = 100;
        img = [];
        rect = [];
        thresholdValue = 0;
        filterSize = 0;
        smoothingStructuringElementSize = 0
        fillHolesAndClean = 0
        t = [];
        fs = 1;
        umperpix = 1;
        e = [];
        e_original = [];
        seg = [];
        bw_caps = [];
        mask = 1;
        area = [];
        diam = [];
        dist_caps = [];

    end

    methods (Access = private)

        function diam = calculate_diam(app, A)
            %stats = regionprops(app.bw_caps,'Centroid');
            %app.dist_caps = ((stats(1).Centroid(1)-stats(2).Centroid(1)).^2+(stats(1).Centroid(2)-stats(2).Centroid(2)).^2).^0.5;
            app.dist_caps = find_dist_caps(app.bw_caps, app.mask, app.seg);
            diam = A / app.dist_caps;

            %app.fs = 1 / mean(diff(app.t));
            if isempty(app.t)
                app.t = (1:length(diam))/app.fs;
            end
            figure, plot(diam), ylabel('diam (pixels)'), xlabel('frame #')
            %figure, spectrogram(highpass(A,0.5,fs),round(15*fs),[],[],fs,'yaxis'), title('Area')
            %figure, spectrogram(highpass(squeeze(mean(app.img,[1 2])),0.5,fs),round(15*fs),[],[],fs,'yaxis'), title('MPI')
            %figure, spectrogram(A,round(15*fs),[],[],fs,'yaxis'), title('Area')
            %figure, spectrogram(squeeze(mean(app.img,[1 2])),round(15*fs),[],[],fs,'yaxis'), title('MPI')
        end

        function A = calculate_area(app)
            A = squeeze(sum(app.seg,[1 2]));
            figure, set(gcf,'color','w')
            plot(A), ylabel('Area (pixels)'), xlabel('frame #')
        end


        function clearUserInput(app)
            app.waitingForInput = false;
            app.thresholdValue = 0;
            app.filterSize = 0;
            %smoothingStructuringElementSize
            %fillHolesAndClean
            app.e = [];
            app.e_original = [];
            app.seg = [];
            app.bw_caps = [];
            app.mask = 1;
            app.area = [];
            app.diam = [];
            app.dist_caps = [];
        end

        function resetApp(app)
            app.img = [];
            app.rect = [];
            app.seriesCount = 1;
            app.t = [];
            app.fs = 1;
            app.umperpix = 1;

            clearUserInput(app)
            app.SelectDirectoryTextArea.Value = '';
            app.SliceProgressPanel_TextArea.Value = '';
            app.RunComputationPanel_TextArea.Value = '';
            app.ThresholdPanelValueEditField.Value = 0;
            app.LIFSeriesPanel_LIFSeriesNumberEditField.Value = 1;
            app.LIFSeriesPanel_UmPerPixEditField.Value = 1;
            app.TIFFrequencyPanel_UmPerPixEditField.Value = 1;
            app.TIFFrequencyPanel_FrequencyEditField.Value = 1;
        end

        function [] = readLIF(app, imgList, LIFSeriesNumber)

            dat=cell(1,5);
            dat{1,1}=imgList(LIFSeriesNumber).Name;           % Name of image
            dat{1,2}=numel(imgList(LIFSeriesNumber).Channels);% number of channel
            [dimType, dimSize]=GetDimensionInfo(imgList(LIFSeriesNumber).Dimensions);
            dat{1,3}=dimType;
            dat{1,4}=int2str(dimSize');
            dat{1,5}=false;

            framerange = [1 inf];
            % -=- Set up framerange -=-
            if strcmp('X-Y-T',dat{1,3})
                framerange=[max([framerange(1) 1]) ... % first frame is 1, not 0!
                    min([framerange(2) ...
                    str2double(imgList(LIFSeriesNumber).Dimensions(3).NumberOfElements)])];
            else
                warning('Framerange is supported only for X-Y-T data.')
                framerange=[0 imgList(LIFSeriesNumber).Dimensions(3).NumberOfElements];
            end
            if str2double(imgList(LIFSeriesNumber).Dimensions(3).BitInc)~=0
                warning('Framerange is supported only for BitInc=0.')
                framerange=[0 imgList(LIFSeriesNumber).Dimensions(3).NumberOfElements];
            end

            imgData  = ReadAnImageData(imgList(LIFSeriesNumber),app.filePath,framerange);
            imgStruct= ReconstructImage(imgList(LIFSeriesNumber),imgData,framerange);
            imgStruct.Name            = dat{1,1};
            imgStruct.Type            = dat{1,3};
            imgStruct.NumberOfChannel = dat{1,2};
            imgStruct.AllocatedFrames=imgList(LIFSeriesNumber).Dimensions(3).NumberOfElements;
            imgStruct.SeriesNames = {dat{:,1}};
            dt = str2double(imgStruct.Info.Dimensions(3).Length) / ...
                str2double(imgStruct.Info.Dimensions(3).NumberOfElements);
            imgStruct.Info.Dimensions(3).NumberOfElements = ...
                num2str(size(imgStruct.Image{1},4));
            imgStruct.Info.Dimensions(3).Origin = ...
                num2str((framerange(1)-1)*dt,'%01.6e');
            imgStruct.Info.Dimensions(3).Length = ...
                num2str((diff(framerange)+1)*dt,'%01.6e');
            imgout=imgStruct;

            app.fs = str2num(imgout.Info.Dimensions(3).NumberOfElements)/str2num(imgout.Info.Dimensions(3).Length);
            app.t = [0:str2num(imgout.Info.Dimensions(3).NumberOfElements)-1]/app.fs;
            app.umperpix = app.LIFSeriesPanel_UmPerPixEditField.Value;
            if app.umperpix == 0
                app.umperpix = 1e6*str2num(imgout.Info.Dimensions(2).Length)/str2num(imgout.Info.Dimensions(2).NumberOfElements);
            end
            app.img = squeeze(imgout.Image{1});
        end

        function tiffData = readTif(app, tiffPath)
            reader = bfGetReader(tiffPath);
            %nSeries = reader.getSeriesCount();
            nFrames = reader.getImageCount();
            height = reader.getSizeY();
            width  = reader.getSizeX();
            %bitDepth = reader.getBitsPerPixel();  % optional
            dtype = 'uint16';  % change if needed

            % Preallocate
            tiffData = zeros(height, width, nFrames, dtype);

            % Disable logging (silence the verbose plane info)
            loci.common.DebugTools.enableLogging('ERROR');  % suppress INFO logs

            % Read all frames
            for i = 1:nFrames
                tiffData(:,:,i) = bfGetPlane(reader, i);
            end

            reader.close();

        end

        function dsFactor = setDSFactor(app)
            imageSize = size(app.img);
            nFrames = imageSize(3);
            dsFactor = 100;
            if nFrames/app.maxPreviewFrames > dsFactor
                dsFactor = round(nFrames/app.maxPreviewFrames);
            else
                dsFactor = max(1, round(nFrames/app.maxPreviewFrames));
            end
        end
    end

    methods (Access = public)

        function [] = closePopup(app)
            figs = findall(0, 'type', 'figure');
            numFigs = length(figs);
            for k = 1:numFigs
                if ~strcmp(figs(k).Name, 'MATLAB App')
                    close(figs(k))
                end
            end
        end
    end

    % Callbacks that handle component events
    methods (Access = private)

        % Code that executes after component creation
        function startupFcn(app)
            % Add the functions/ and utilities/ subdirectories to the path
            addpath(fullfile(app.currentDir, 'func'), fullfile(app.currentDir, 'util'));
        end

        % Button pushed function: SelectDirectoryButton
        function SelectDirectoryButtonPushed(app, event)
            f = figure('Position', [-100 -100 0 0]); % create a dummy figure so that uigetfile doesn't minimize our GUI
            %selectedDir = uigetdir(app.currentDir);
            [selectedFile, parentFolder] = uigetfile({'*.lif;*.mat;*.tif'});
            %[parentFolder, ~, ~] = fileparts(string(selectedDir));

            app.defaultUigetdir = parentFolder;
            % Check if a directory was selected (uigetdir returns 0 if the user cancels the dialog)
            delete(f);
            if selectedFile ~= 0
                % Store the selected directory path in the Edit Field
                app.filePath = fullfile(parentFolder, selectedFile);
                app.SelectDirectoryTextArea.Value = app.filePath;
            end
        end

        % Button pushed function: HomePanel_ContinueButton
        function HomePanel_ContinueButtonPushed(app, event)
            [filepath, name, ext] = fileparts(app.filePath);
            if strcmp(ext, '.lif')
                fileID = fopen(app.filePath, 'r');
                [fp, xmlHdrStr] = ReadXMLPart(fileID);
                xmlList=XMLtxt2cell(xmlHdrStr);
                lifVersion = GetLifVersion(xmlList(1,:)); % lifVersion is double scalar

                % Reading Image Info
                imgList = GetImageDescriptionList(xmlList);% imgList is struct vector
                % memoryList is cell array (n x 4)
                % ID(string), startPoint(uint64), sizeOfMemory, Index(double)
                imgList  = ReadObjectMemoryBlocks(fp,lifVersion,imgList);
                fclose(fp);
                app.seriesCount = numel(imgList);
                message = '';
                for n=1:app.seriesCount
                    message = [message, {strcat(int2str(n), '. ', imgList(n).Name)}];
                end
                app.LIFSeriesPanel_TextArea.Value = message;
                app.HomePanel.Visible = 'off';
                app.LIFSeriesPanel.Visible = 'on';
                app.waitingForInput = true;
                waitfor(app, 'waitingForInput', false);

                LIFSeriesNumber = app.LIFSeriesPanel_LIFSeriesNumberEditField.Value;
                readLIF(app, imgList, LIFSeriesNumber)
            elseif strcmp(ext, '.mat')
                app.HomePanel.Visible = 'off';
                app.img = load(app.filePath).img;

            elseif strcmp(ext, '.tif')
                app.HomePanel.Visible = 'off';
                app.LIFSeriesPanel.Visible = 'off';
                app.TIFFrequencyPanel.Visible = 'on';
                app.waitingForInput = true;
                waitfor(app, 'waitingForInput', false);

                app.fs = app.TIFFrequencyPanel_FrequencyEditField.Value;
                app.umperpix = app.TIFFrequencyPanel_UmPerPixEditField.Value;

                try
                    [app.img, ~] = imread_big(app.filePath);
                catch
                    warning('imread_big failed; falling back to imread loop.');
                    numImages = size(imfinfo(app.filePath), 1);
                    imageSize = size(imread(app.filePath));
                    app.img = zeros(imageSize(1), imageSize(2), numImages);
                    for i = 1:numImages
                        app.img(:, :, i) = imread(app.filePath,i);
                    end
                end

            end

            app.dsFactor = setDSFactor(app);
            images = app.img(:, :, 1:app.dsFactor:end);
            % cropping
            %app.LIFSeriesPanel.Visible = 'off';
            %app.TIFFrequencyPanel.Visible = 'off';
            app.CroppingPanel.Visible = 'on';
            imagei(images), colormap gray
            roi = drawrectangle();
            wait(roi);
            app.rect = round(roi.Position);
            images = images(app.rect(2):app.rect(2)+app.rect(4),app.rect(1):app.rect(1)+app.rect(3),:);
            closePopup(app)
            %app.ThresholdPanel.Visible = 'on';
            app.CroppingPanel.Visible = 'off';
            app.waitingForInput = true;
            %[app.e, app.seg, app.bw_caps, app.mask] = find_img_edges(app, app.img, [], 1);
            images = findEdges(app, images);
            images = makeMask(app, images);
            %dilateMask(app)
            images = makeCaps(app, images);
            app.SliceProgressPanel.Visible = 'on';
            images = makeSeg(app, images);
            imagei({images images images},{repmat(app.bw_caps | app.mask,[1 1 size(app.seg,3)]) app.seg app.e})

        end

        % Button pushed function: ThresholdPanelBackButton
        function ThresholdPanelBackButtonPushed(app, event)
            app.waitingForInput = false;
            app.ThresholdPanel.Visible = 'off';
            app.HomePanel.Visible = 'off';
        end

        % Button pushed function: ThresholdPanelContinueButton
        function ThresholdPanelContinueButtonPushed(app, event)
            app.ThresholdPanelLabel_3.Text = class(app.thresholdValue);
            app.waitingForInput = false;
            app.ThresholdPanel.Visible = 'off';
            app.MaskingPanel.Visible = 'on';
        end

        % Value changed function: ThresholdPanelValueEditField
        function ThresholdPanelValueEditFieldValueChanged(app, event)
            value = app.ThresholdPanelValueEditField.Value;
            app.thresholdValue = value;
        end

        % Callback function
        function FilterSizeEditFieldValueChanged(app, event)
            value = app.FilterSizeEditField.Value;
            app.filterSize = value;
        end

        % Callback function
        function SmoothingStructuringElementSizeEditFieldValueChanged(app, event)
            value = app.SmoothingStructuringElementSizeEditField.Value;
            app.smoothingStructuringElementSize = value;
        end

        % Callback function
        function Fillholesandclean1foryes0fornoEditFieldValueChanged(app, event)
            value = app.Fillholesandclean1foryes0fornoEditField.Value;
            app.fillHolesAndClean = value;
        end

        % Button pushed function: DilationPanel_ContinueButton
        function DilationPanel_ContinueButtonPushed(app, event)
            app.waitingForInput = false;
        end

        % Button pushed function: SaveResultsButton
        function SaveResultsButtonPushed(app, event)
            f = figure('Position', [-100 -100 0 0]); % create a dummy figure so that uigetfile doesn't minimize our GUI
            %selectedDir = uigetdir(app.currentDir);
            [~,name,~] = fileparts(app.filePath);
            defaultSaveName = [name '_results.mat'];
            [filename, path] = uiputfile(defaultSaveName);
            % Check if a directory was selected (uigetdir returns 0 if the user cancels the dialog)
            delete(f);
            if path ~= 0
                % Create the full file path
                full_file_path = fullfile(path, filename);
                full_file_path = string(full_file_path);
                %app.SliceProgressPanel_Label.Text = full_file_path;
                % Save the data
                t = app.t;
                fs = app.fs;
                umperpix = app.umperpix;
                img = app.img;
                rect = app.rect;
                area = app.area;
                bw_caps = app.bw_caps;
                mask = app.mask;
                e = app.e;
                seg = app.seg;
                diam = app.diam;
                dist_caps = app.dist_caps;
                save(full_file_path, ...
                    "t", ...
                    "fs", ...
                    "umperpix", ...
                    "img", ...
                    'rect', ...
                    'area', ...
                    'bw_caps', ...
                    'mask', ...
                    'e', ...
                    'seg', ...
                    'diam', ...
                    'dist_caps', ...
                    '-v7.3' ...
                );
                message = strcat("results saved to ", full_file_path);
                title = 'Results Saved';
                icon = 'success';
                uialert(app.UIFigure, message, title, 'Icon', icon);


                app.RunComputationPanel.Visible = 'off';
                app.HomePanel.Visible = 'on';
                resetApp(app)
            end
        end

        % Button pushed function: RunButton
        function RunButtonPushed(app, event)
            app.img = app.img(app.rect(2):app.rect(2)+app.rect(4),app.rect(1):app.rect(1)+app.rect(3),:);

            findEdges(app, app.img);
            makeMask(app, app.img);
            app.SliceProgressPanel.Visible = 'on';
            makeSeg(app, app.img);
            app.SliceProgressPanel.Visible = 'off';
            app.RunComputationPanel.Visible = 'on'; % gather the user input from panel_2

            app.RunComputationPanel_TextArea.Value = 'Masks and caps created.';
            message = 'calculating area and diameter.';
            app.RunComputationPanel_TextArea.Value = [app.RunComputationPanel_TextArea.Value(:)', {message}];
            app.waitingForInput = true;
            %[app.e, app.seg, app.bw_caps, app.mask] = find_img_edges(app, app.img, app.bw_caps, app.mask);
            app.area = calculate_area(app);
            app.diam = calculate_diam(app, app.area);
            message = 'Done.';
            app.RunComputationPanel_TextArea.Value = [app.RunComputationPanel_TextArea.Value(:)', {message}];
        end

        % Button pushed function: RedoMaskButton
        function RedoMaskButtonPushed(app, event)
            clearUserInput(app)
            app.waitingForInput = true;

            app.dsFactor = setDSFactor(app);
            images = app.img(:, :, 1:app.dsFactor:end);
            images = images(app.rect(2):app.rect(2)+app.rect(4),app.rect(1):app.rect(1)+app.rect(3),:);

            images = findEdges(app, images);
            images = makeMask(app, images);
            %dilateMask(app)
            images = makeCaps(app, images);
            app.SliceProgressPanel.Visible = 'on';
            images = makeSeg(app, images);
            imagei({images images images},{repmat(app.bw_caps | app.mask,[1 1 size(app.seg,3)]) app.seg app.e})
        end

        % Button pushed function: LIFSeriesPanel_NextButton
        function LIFSeriesPanel_NextButtonPushed(app, event)
            lifSeriesNum = app.LIFSeriesPanel_LIFSeriesNumberEditField.Value;
            message = '';
            if lifSeriesNum > app.seriesCount
                message = strcat('The series index you entered is greater than the number of series, ', int2str(app.seriesCount), ', in the LIF.');
            elseif lifSeriesNum < 1
                message = 'The series index starts at 1.';
            end

            if (message ~= "")
                uialert(app.UIFigure, message, "Invalid Value");
            else
            app.LIFSeriesPanel.Visible = 'off';
            app.TIFFrequencyPanel.Visible = 'off';
            app.waitingForInput = false;
            end
        end

        % Button pushed function: TIFFrequencyPanel_NextButton
        function TIFFrequencyPanel_NextButtonPushed(app, event)
            frequency = app.TIFFrequencyPanel_FrequencyEditField.Value;
            message = '';
            if frequency <= 0
                message = 'Frequency must be greater than 0.';
            end

            if (message ~= "")
                uialert(app.UIFigure, message, "Invalid Value");
            else
            app.TIFFrequencyPanel.Visible = 'off';
            app.waitingForInput = false;
            end
        end
    end

    % Component initialization
    methods (Access = private)

        % Create UIFigure and components
        function createComponents(app)

            % Create UIFigure and hide until all components are created
            app.UIFigure = uifigure('Visible', 'off');
            app.UIFigure.Position = [100 100 640 480];
            app.UIFigure.Name = 'MATLAB App';

            % Create RunComputationPanel
            app.RunComputationPanel = uipanel(app.UIFigure);
            app.RunComputationPanel.Title = 'Computation';
            app.RunComputationPanel.Position = [93 15 461 453];

            % Create SaveResultsButton
            app.SaveResultsButton = uibutton(app.RunComputationPanel, 'push');
            app.SaveResultsButton.ButtonPushedFcn = createCallbackFcn(app, @SaveResultsButtonPushed, true);
            app.SaveResultsButton.Position = [178 100 100 23];
            app.SaveResultsButton.Text = 'Save Results';

            % Create ProgressTextAreaLabel_2
            app.ProgressTextAreaLabel_2 = uilabel(app.RunComputationPanel);
            app.ProgressTextAreaLabel_2.HorizontalAlignment = 'right';
            app.ProgressTextAreaLabel_2.Position = [207 356 53 22];
            app.ProgressTextAreaLabel_2.Text = 'Progress';

            % Create RunComputationPanel_TextArea
            app.RunComputationPanel_TextArea = uitextarea(app.RunComputationPanel);
            app.RunComputationPanel_TextArea.Editable = 'off';
            app.RunComputationPanel_TextArea.Position = [63 184 337 170];

            % Create SliceProgressPanel
            app.SliceProgressPanel = uipanel(app.UIFigure);
            app.SliceProgressPanel.Title = 'Slice Progress';
            app.SliceProgressPanel.Position = [93 15 461 453];

            % Create ProgressTextAreaLabel
            app.ProgressTextAreaLabel = uilabel(app.SliceProgressPanel);
            app.ProgressTextAreaLabel.HorizontalAlignment = 'right';
            app.ProgressTextAreaLabel.Position = [203 356 53 22];
            app.ProgressTextAreaLabel.Text = 'Progress';

            % Create SliceProgressPanel_TextArea
            app.SliceProgressPanel_TextArea = uitextarea(app.SliceProgressPanel);
            app.SliceProgressPanel_TextArea.Editable = 'off';
            app.SliceProgressPanel_TextArea.Position = [59 256 337 98];

            % Create RunButton
            app.RunButton = uibutton(app.SliceProgressPanel, 'push');
            app.RunButton.ButtonPushedFcn = createCallbackFcn(app, @RunButtonPushed, true);
            app.RunButton.Position = [178 71 100 23];
            app.RunButton.Text = 'Run';

            % Create RedoMaskButton
            app.RedoMaskButton = uibutton(app.SliceProgressPanel, 'push');
            app.RedoMaskButton.ButtonPushedFcn = createCallbackFcn(app, @RedoMaskButtonPushed, true);
            app.RedoMaskButton.Position = [178 108 100 23];
            app.RedoMaskButton.Text = 'Redo Mask';

            % Create SliceProgressPanel_Label
            app.SliceProgressPanel_Label = uilabel(app.SliceProgressPanel);
            app.SliceProgressPanel_Label.VerticalAlignment = 'top';
            app.SliceProgressPanel_Label.WordWrap = 'on';
            app.SliceProgressPanel_Label.FontSize = 14;
            app.SliceProgressPanel_Label.Position = [51 157 354 69];
            app.SliceProgressPanel_Label.Text = 'Please check that the caps and and the mask look good. If adjustments are needed, click Redo Mask. If everything looks good, click Run to start the computation.';

            % Create CappingPanel
            app.CappingPanel = uipanel(app.UIFigure);
            app.CappingPanel.Title = 'Capping';
            app.CappingPanel.Position = [93 15 461 453];

            % Create CappingPanel_Label1
            app.CappingPanel_Label1 = uilabel(app.CappingPanel);
            app.CappingPanel_Label1.VerticalAlignment = 'top';
            app.CappingPanel_Label1.WordWrap = 'on';
            app.CappingPanel_Label1.Position = [45 279 355 63];
            app.CappingPanel_Label1.Text = 'Click and drag to draw a line to cap off the ends. Move the line and dbl click when satisfied. (Depending on the version of Matlab, you might have to move the end points';

            % Create Label_3
            app.Label_3 = uilabel(app.CappingPanel);
            app.Label_3.VerticalAlignment = 'top';
            app.Label_3.WordWrap = 'on';
            app.Label_3.Position = [45 203 355 56];
            app.Label_3.Text = 'Note: when you draw the caps, please make sure that 1) the caps cuts through the dilated edges, 2) the caps are orthogonal to the vessel to the best of your ability.';

            % Create DilationPanel
            app.DilationPanel = uipanel(app.UIFigure);
            app.DilationPanel.Title = 'Dilation';
            app.DilationPanel.Position = [93 15 461 453];

            % Create DilationPanel_Label1
            app.DilationPanel_Label1 = uilabel(app.DilationPanel);
            app.DilationPanel_Label1.VerticalAlignment = 'top';
            app.DilationPanel_Label1.WordWrap = 'on';
            app.DilationPanel_Label1.Position = [58 369 346 21];
            app.DilationPanel_Label1.Text = 'Mask Step 3: dilate the mask to include the edges in all frames.';

            % Create DilationPanel_Label2
            app.DilationPanel_Label2 = uilabel(app.DilationPanel);
            app.DilationPanel_Label2.VerticalAlignment = 'top';
            app.DilationPanel_Label2.WordWrap = 'on';
            app.DilationPanel_Label2.Position = [58 284 337 59];
            app.DilationPanel_Label2.Text = 'The current mask is in red. The edges are shown in green. Make sure the mask includes all of the edges of interest. I often start by dilating with a structuring element of size 5 pixels. Enter 0 to stop dilating.';

            % Create WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel
            app.WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel = uilabel(app.DilationPanel);
            app.WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel.VerticalAlignment = 'top';
            app.WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel.WordWrap = 'on';
            app.WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel.Position = [79 194 258 39];
            app.WhatsizestructuringelementdoyouwanttousetodilatethemaskLabel.Text = 'Structuring element size for dilating the mask?';

            % Create DilationPanel_SizeEditField
            app.DilationPanel_SizeEditField = uieditfield(app.DilationPanel, 'numeric');
            app.DilationPanel_SizeEditField.Position = [348 214 27 22];

            % Create DilationPanel_ContinueButton
            app.DilationPanel_ContinueButton = uibutton(app.DilationPanel, 'push');
            app.DilationPanel_ContinueButton.ButtonPushedFcn = createCallbackFcn(app, @DilationPanel_ContinueButtonPushed, true);
            app.DilationPanel_ContinueButton.Position = [304 49 100 23];
            app.DilationPanel_ContinueButton.Text = 'Continue';

            % Create MaskingPanel
            app.MaskingPanel = uipanel(app.UIFigure);
            app.MaskingPanel.Title = 'Mask Adjustment';
            app.MaskingPanel.Position = [93 15 461 453];

            % Create Label
            app.Label = uilabel(app.MaskingPanel);
            app.Label.VerticalAlignment = 'top';
            app.Label.WordWrap = 'on';
            app.Label.Position = [54 280 354 52];
            app.Label.Text = 'Now, in the pop-up window adjust the mask by drawing a tight bounding box around the vessel.';

            % Create Label_2
            app.Label_2 = uilabel(app.MaskingPanel);
            app.Label_2.VerticalAlignment = 'top';
            app.Label_2.WordWrap = 'on';
            app.Label_2.Position = [54 232 354 52];
            app.Label_2.Text = 'Double click your bounding box when done.';

            % Create ThresholdPanel
            app.ThresholdPanel = uipanel(app.UIFigure);
            app.ThresholdPanel.Tooltip = {''};
            app.ThresholdPanel.Title = 'Threshold ';
            app.ThresholdPanel.Position = [93 15 461 453];

            % Create ThresholdValueEditFieldLabel
            app.ThresholdValueEditFieldLabel = uilabel(app.ThresholdPanel);
            app.ThresholdValueEditFieldLabel.FontWeight = 'bold';
            app.ThresholdValueEditFieldLabel.Position = [52 225 98 22];
            app.ThresholdValueEditFieldLabel.Text = 'Threshold Value';

            % Create ThresholdPanelValueEditField
            app.ThresholdPanelValueEditField = uieditfield(app.ThresholdPanel, 'numeric');
            app.ThresholdPanelValueEditField.ValueChangedFcn = createCallbackFcn(app, @ThresholdPanelValueEditFieldValueChanged, true);
            app.ThresholdPanelValueEditField.Tooltip = {'Enter 0 to use a seperate threshold calculated for each image. Enter an integer < 0 to use a spatially varying threshold for each image. The absolute value of this number is the size of the dilating element.'};
            app.ThresholdPanelValueEditField.Position = [168 225 46 22];

            % Create ThresholdPanelLabel_2
            app.ThresholdPanelLabel_2 = uilabel(app.ThresholdPanel);
            app.ThresholdPanelLabel_2.VerticalAlignment = 'top';
            app.ThresholdPanelLabel_2.WordWrap = 'on';
            app.ThresholdPanelLabel_2.FontSize = 14;
            app.ThresholdPanelLabel_2.Position = [52 318 357 52];
            app.ThresholdPanelLabel_2.Text = 'First, specify the the Threshold Value below to use for the segmentation. You can use the pop-up window to help you choose the Threshold Value.';

            % Create ThresholdPanelBackButton
            app.ThresholdPanelBackButton = uibutton(app.ThresholdPanel, 'push');
            app.ThresholdPanelBackButton.ButtonPushedFcn = createCallbackFcn(app, @ThresholdPanelBackButtonPushed, true);
            app.ThresholdPanelBackButton.Position = [55 52 100 23];
            app.ThresholdPanelBackButton.Text = 'Back';

            % Create ThresholdPanelContinueButton
            app.ThresholdPanelContinueButton = uibutton(app.ThresholdPanel, 'push');
            app.ThresholdPanelContinueButton.ButtonPushedFcn = createCallbackFcn(app, @ThresholdPanelContinueButtonPushed, true);
            app.ThresholdPanelContinueButton.Position = [304 52 100 23];
            app.ThresholdPanelContinueButton.Text = 'Continue';

            % Create ThresholdPanelLabel_3
            app.ThresholdPanelLabel_3 = uilabel(app.ThresholdPanel);
            app.ThresholdPanelLabel_3.FontSize = 14;
            app.ThresholdPanelLabel_3.Position = [52 270 224 22];
            app.ThresholdPanelLabel_3.Text = 'Click Continue when you are done.';

            % Create CroppingPanel
            app.CroppingPanel = uipanel(app.UIFigure);
            app.CroppingPanel.Title = 'Cropping';
            app.CroppingPanel.Position = [93 15 461 453];

            % Create CroppingPanel_Label
            app.CroppingPanel_Label = uilabel(app.CroppingPanel);
            app.CroppingPanel_Label.WordWrap = 'on';
            app.CroppingPanel_Label.FontSize = 14;
            app.CroppingPanel_Label.Position = [52 184 365 143];
            app.CroppingPanel_Label.Text = 'In the pop-up window, select a region and then double click to confirm.';

            % Create TIFFrequencyPanel
            app.TIFFrequencyPanel = uipanel(app.UIFigure);
            app.TIFFrequencyPanel.Title = 'TIF Frequency';
            app.TIFFrequencyPanel.Position = [93 15 461 453];

            % Create EnterthefrequencyofrecordingEditFieldLabel
            app.EnterthefrequencyofrecordingEditFieldLabel = uilabel(app.TIFFrequencyPanel);
            app.EnterthefrequencyofrecordingEditFieldLabel.HorizontalAlignment = 'right';
            app.EnterthefrequencyofrecordingEditFieldLabel.Position = [67 288 176 22];
            app.EnterthefrequencyofrecordingEditFieldLabel.Text = 'Enter the frequency of recording';

            % Create TIFFrequencyPanel_FrequencyEditField
            app.TIFFrequencyPanel_FrequencyEditField = uieditfield(app.TIFFrequencyPanel, 'numeric');
            app.TIFFrequencyPanel_FrequencyEditField.Limits = [1 Inf];
            app.TIFFrequencyPanel_FrequencyEditField.ValueDisplayFormat = '%0.0d';
            app.TIFFrequencyPanel_FrequencyEditField.Position = [259 288 38 22];
            app.TIFFrequencyPanel_FrequencyEditField.Value = 1;

            % Create EntermicronsperpixelLabel
            app.EntermicronsperpixelLabel = uilabel(app.TIFFrequencyPanel);
            app.EntermicronsperpixelLabel.HorizontalAlignment = 'right';
            app.EntermicronsperpixelLabel.Position = [70 253 128 22];
            app.EntermicronsperpixelLabel.Text = 'Enter microns per pixel';

            % Create TIFFrequencyPanel_UmPerPixEditField
            app.TIFFrequencyPanel_UmPerPixEditField = uieditfield(app.TIFFrequencyPanel, 'numeric');
            app.TIFFrequencyPanel_UmPerPixEditField.ValueDisplayFormat = '%0.0d';
            app.TIFFrequencyPanel_UmPerPixEditField.Position = [259 253 38 22];
            app.TIFFrequencyPanel_UmPerPixEditField.Value = 1;

            % Create TIFFrequencyPanel_NextButton
            app.TIFFrequencyPanel_NextButton = uibutton(app.TIFFrequencyPanel, 'push');
            app.TIFFrequencyPanel_NextButton.ButtonPushedFcn = createCallbackFcn(app, @TIFFrequencyPanel_NextButtonPushed, true);
            app.TIFFrequencyPanel_NextButton.Position = [312 82 100 23];
            app.TIFFrequencyPanel_NextButton.Text = 'Next';

            % Create LIFSeriesPanel
            app.LIFSeriesPanel = uipanel(app.UIFigure);
            app.LIFSeriesPanel.Title = 'LIF Series';
            app.LIFSeriesPanel.Position = [93 15 461 453];

            % Create ChooseseriesinLIFLabel
            app.ChooseseriesinLIFLabel = uilabel(app.LIFSeriesPanel);
            app.ChooseseriesinLIFLabel.HorizontalAlignment = 'right';
            app.ChooseseriesinLIFLabel.Position = [79 163 157 22];
            app.ChooseseriesinLIFLabel.Text = 'Choose a series index in LIF';

            % Create LIFSeriesPanel_LIFSeriesNumberEditField
            app.LIFSeriesPanel_LIFSeriesNumberEditField = uieditfield(app.LIFSeriesPanel, 'numeric');
            app.LIFSeriesPanel_LIFSeriesNumberEditField.Position = [247 163 48 22];
            app.LIFSeriesPanel_LIFSeriesNumberEditField.Value = 1;

            % Create LIFSeriesPanel_NextButton
            app.LIFSeriesPanel_NextButton = uibutton(app.LIFSeriesPanel, 'push');
            app.LIFSeriesPanel_NextButton.ButtonPushedFcn = createCallbackFcn(app, @LIFSeriesPanel_NextButtonPushed, true);
            app.LIFSeriesPanel_NextButton.Position = [327 70 100 23];
            app.LIFSeriesPanel_NextButton.Text = 'Next';

            % Create LIFSeriesTextAreaLabel
            app.LIFSeriesTextAreaLabel = uilabel(app.LIFSeriesPanel);
            app.LIFSeriesTextAreaLabel.HorizontalAlignment = 'right';
            app.LIFSeriesTextAreaLabel.Position = [79 259 60 22];
            app.LIFSeriesTextAreaLabel.Text = 'LIF Series';

            % Create LIFSeriesPanel_TextArea
            app.LIFSeriesPanel_TextArea = uitextarea(app.LIFSeriesPanel);
            app.LIFSeriesPanel_TextArea.Editable = 'off';
            app.LIFSeriesPanel_TextArea.Position = [151 208 144 124];

            % Create EnterumperpixelEditFieldLabel
            app.EnterumperpixelEditFieldLabel = uilabel(app.LIFSeriesPanel);
            app.EnterumperpixelEditFieldLabel.Position = [83 128 139 22];
            app.EnterumperpixelEditFieldLabel.Text = 'Enter um per pixel';

            % Create LIFSeriesPanel_UmPerPixEditField
            app.LIFSeriesPanel_UmPerPixEditField = uieditfield(app.LIFSeriesPanel, 'numeric');
            app.LIFSeriesPanel_UmPerPixEditField.Limits = [0 Inf];
            app.LIFSeriesPanel_UmPerPixEditField.Position = [247 128 48 22];
            app.LIFSeriesPanel_UmPerPixEditField.Value = 1;

            % Create HomePanel
            app.HomePanel = uipanel(app.UIFigure);
            app.HomePanel.Title = 'Vessel Diameter and Pulsatility Analysis App';
            app.HomePanel.Position = [93 15 461 453];

            % Create HomePanel_Label1
            app.HomePanel_Label1 = uilabel(app.HomePanel);
            app.HomePanel_Label1.FontWeight = 'bold';
            app.HomePanel_Label1.Position = [100 347 263 39];
            app.HomePanel_Label1.Text = 'Vessel Diameter and Pulsatility Analysis App';

            % Create SelectDirectoryTextArea
            app.SelectDirectoryTextArea = uitextarea(app.HomePanel);
            app.SelectDirectoryTextArea.Position = [54 158 347 37];

            % Create SelectDirectoryButton
            app.SelectDirectoryButton = uibutton(app.HomePanel, 'push');
            app.SelectDirectoryButton.ButtonPushedFcn = createCallbackFcn(app, @SelectDirectoryButtonPushed, true);
            app.SelectDirectoryButton.FontWeight = 'bold';
            app.SelectDirectoryButton.Position = [152 223 151 26];
            app.SelectDirectoryButton.Text = 'Select Directory';

            % Create HomePanel_ContinueButton
            app.HomePanel_ContinueButton = uibutton(app.HomePanel, 'push');
            app.HomePanel_ContinueButton.ButtonPushedFcn = createCallbackFcn(app, @HomePanel_ContinueButtonPushed, true);
            app.HomePanel_ContinueButton.Position = [327 52 75 23];
            app.HomePanel_ContinueButton.Text = 'Continue';

            % Show the figure after all components are created
            app.UIFigure.Visible = 'on';
        end
    end

    % App creation and deletion
    methods (Access = public)

        % Construct app
        function app = app_exported

            % Create UIFigure and components
            createComponents(app)

            % Register the app with App Designer
            registerApp(app, app.UIFigure)

            % Execute the startup function
            runStartupFcn(app, @startupFcn)

            if nargout == 0
                clear app
            end
        end

        % Code that executes before app deletion
        function delete(app)

            % Delete UIFigure when app is deleted
            delete(app.UIFigure)
        end
    end
end
