function changed = export_app_source(mode)
%EXPORT_APP_SOURCE Generate or verify the tracked text form of app.mlapp.
%   EXPORT_APP_SOURCE reads app.mlapp with MATLAB's App Designer code
%   exporter and writes app_exported.m for source review.
%
%   EXPORT_APP_SOURCE('verify') checks that app_exported.m is current and
%   throws an error when it is missing or stale.
%
%   app.mlapp is the editable source of truth. Do not edit app_exported.m.

    if nargin < 1
        mode = 'write';
    end

    mode = validatestring(mode, {'write', 'verify'});
    projectDir = fileparts(mfilename('fullpath'));
    appFile = fullfile(projectDir, 'app.mlapp');
    exportFile = fullfile(projectDir, 'app_exported.m');

    if ~isfile(appFile)
        error('vessel_diameter_pulsatility_analysis_app:MissingApp', ...
            'Cannot find App Designer source: %s', appFile);
    end

    appCode = appdesigner.internal.codegeneration.getAppFileCode(appFile);
    if isempty(appCode)
        error('vessel_diameter_pulsatility_analysis_app:EmptyAppCode', ...
            'MATLAB could not read code from %s.', appFile);
    end

    [~, originalName] = fileparts(appFile);
    exporter = appdesigner.internal.serialization.converter.MLAPPExporter( ...
        exportFile, struct('originalName', originalName));
    exportedCode = exporter.getGeneratedCode(appCode);

    header = sprintf([ ...
        '%% AUTO-GENERATED FROM app.mlapp BY export_app_source.m.\n' ...
        '%% DO NOT EDIT THIS FILE DIRECTLY.\n' ...
        '%% Regenerate with: matlab -batch "export_app_source"\n\n']);
    expected = canonicalizeCode([header exportedCode]);

    if strcmp(mode, 'verify')
        if ~isfile(exportFile)
            error('vessel_diameter_pulsatility_analysis_app:MissingAppExport', ...
                ['app_exported.m is missing. Run: matlab -batch ' ...
                '"export_app_source"']);
        end

        actual = normalizeNewlines(fileread(exportFile));
        if ~strcmp(actual, expected)
            error('vessel_diameter_pulsatility_analysis_app:StaleAppExport', ...
                ['app_exported.m is stale. Run: matlab -batch ' ...
                '"export_app_source"']);
        end

        changed = false;
        fprintf('app_exported.m matches app.mlapp.\n');
        return
    end

    changed = true;
    if isfile(exportFile)
        actual = normalizeNewlines(fileread(exportFile));
        if strcmp(actual, expected)
            changed = false;
            fprintf('app_exported.m is already current.\n');
            return
        end
    end

    fileId = fopen(exportFile, 'wb');
    if fileId < 0
        error('vessel_diameter_pulsatility_analysis_app:ExportNotWritable', ...
            'Cannot write %s.', exportFile);
    end
    cleanup = onCleanup(@() fclose(fileId));

    bytes = unicode2native(expected, 'UTF-8');
    bytesWritten = fwrite(fileId, bytes, 'uint8');
    if bytesWritten ~= numel(bytes)
        error('vessel_diameter_pulsatility_analysis_app:IncompleteExport', ...
            'MATLAB did not finish writing %s.', exportFile);
    end

    fprintf('Generated app_exported.m from app.mlapp.\n');
end

function text = normalizeNewlines(text)
    text = regexprep(char(text), '\r\n?', '\n');
end

function text = canonicalizeCode(text)
    text = normalizeNewlines(text);
    text = regexprep(text, '[ \t]+(\n|$)', '$1');
    text = regexprep(text, '\n*$', '');
    text = [text newline];
end
